import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { dbInitialize } from './api/db/index'

export default function Home() {

  dbInitialize();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
            Test entitites
          </p>
        </div>
      </main>
    </>
  )
}
